### ISSUE TITLE
[Feat] Implement `<Polyline>` component.

### ISSUE THREAD

**Issue by benschlegel** [visgl/react-google-maps#105]
### Target Use Case

Have a react component for `google.maps.Polyline` similar to `<Marker>`/the other components.

Is this something this project plans on doing? I'm asking because I was planning on making a PR that implements this, but wanted to ask if this is in the scope of this project before putting in work into the PR.

### Proposal

```jsx
<Polyline {...props />
```

**Comment by JoshuaSkootsky** [comment]
I am also interested in this!

**Comment by shaunmitchellve** [comment]
I would like to +1 this. I've just recently had to do this for displaying multiple routes on the map with click handlers, since the directionrenderer doesn't expose the click event.

**Comment by guilhermenunes09** [comment]
This would be really helpful, specially dealing with GeoJson data. That being said, is there a workaround for using its libraries, I couldn't find it yet. Thanks!

**Comment by nearwood** [comment]
> This would be really helpful, specially when dealing with GeoJson data. That being said, is there a workaround for using its libraries, I couldn't find it yet. Thanks!

What coincidence, I just started using this library today for a side project and needed the same.

Here's what I used (`<APIProvider>` is in a parent component): 

```ts
import React from 'react';
import { Map, useMap, useMapsLibrary } from '@vis.gl/react-google-maps';

export default function MyMap() {
  const map = useMap();
  const maps = useMapsLibrary("maps");
  const position = { lat: 0, lng: -180 };

  const flightPlanCoordinates = [
    { lat: 37.772, lng: -122.214 },
    { lat: 21.291, lng: -157.821 },
    { lat: -18.142, lng: 178.431 },
    { lat: -27.467, lng: 153.027 },
  ];

  if (!maps) {
    return null;
  }

  const flightPath = new maps.Polyline({
    path: flightPlanCoordinates,
    geodesic: true,
    strokeColor: "#FF0000",
    strokeOpacity: 1.0,
    strokeWeight: 2,
  });

  flightPath.setMap(map);

  return (
    <Map
      zoom={3}
      center={position}
      gestureHandling={'greedy'}
      disableDefaultUI={true}
    />
  );
}

```

**Comment by guilhermenunes09** [comment]
>
> What coincidence, I just started using this library today for a side project and needed the same.
> 

Thanks, @nearwood! It works great! I'm sure it will help lots of people who are trying to figure this out. I'm going to try to create a Polygon component based on that.

**Comment by shane806** [comment]
Is there still interest in a generalized `<Polyline>` component? I'll give it a shot if so.

**Comment by usefulthink** [comment]
Absolutely, please have a look [at our contributing docs](https://visgl.github.io/react-google-maps/docs/contributing) and [the guide to write and add examples](https://visgl.github.io/react-google-maps/docs/guides/writing-examples)

The best course of action would be to create a new example (e.g. `geometry-overlays`) that contains implementations for a suggested `Polygon`/`Polyline`/whatever else component. People who want to use it can instantly start by copying those components into their code (if we look at the success of https://github.com/shadcn-ui/ui, that doesn't seem to bother people very much).

**Comment by ArielBenichou** [comment]
So here [a small PR](https://github.com/visgl/react-google-maps/pull/178), in the subject, for now only implementing the `Circle` component.

**Comment by Fabioni** [comment]
Now, that we have Polygon and Circle, Polyline should be easy, right? 😁

**Comment by ArielBenichou** [comment]
@Fabioni I want to say just find and replace `Polygon` with `Polyline` and i guess it should work, easy as that.
maybe add one or two props special for the Polygon, from what i remember seeing they both have very similar APIs

**Comment by Fabioni** [comment]
> @Fabioni I want to say just find and replace `Polygon` with `Polyline` and i guess it should work, easy as that.
> maybe add one or two props special for the Polygon, from what i remember seeing they both have very similar APIs

I also think so. I even thought it's not worth it to make a pull request for that because it should be so straight forward for the one who implemented the polygon.
What do you think?

**Comment by ArielBenichou** [comment]
> I also think so. I even thought it's not worth it to make a pull request for that because it should be so straight forward for the one who implemented the polygon. What do you think?

At first i thought adding also the `Polyline`, but i didn't yet get the feedback from the PR, so i didn't want to do double work  for each change request by the PR.

First of all, I think that when/if this is will part of the core library we want to give the `Polyline` out-of-the-box, you should not created locally the `Polyline` but get the `Polygon` from the lib. it feel wrong.

### So, should we add this to the example?
On one hand, we are in the copy-pasta m.o. that required the dev to look at the copied code, so just copy the code and add/remove your changes, and implement the `Rectangle` and `Polyline` basing yourself on the `Circle` and `Polygon`.

The reason those geometry components are not part of the lib, and are just an example, is because we want to wait and see how those mature, and what should be the final API. (for example I thought about it, and the `encodedPaths` of the `Polygon` should not be part of the component, you should use in the parent a kind of `useEncodedPath` or something) 

On the other hand, if every dev come here and copy the `Polygon` just to transform it to a `Polyline`, it will be convenient for everybody to have it accessible to just copy.

If you have some time to kill, maybe implement the `Rectangle` and `Polyline` add them to the example. it will not hurt. 😃

**Comment by usefulthink** [comment]
Agreed. Even if it's just copy and paste, it could help us figuring out what needs to be done to get all the types of geometry added.

**Comment by Fabioni** [comment]
So do we actually have all shapes now implemented in a nice react way? (Polyline, Polygone, Circle)

**Comment by usefulthink** [comment]
Not all of them, but [the components written](https://github.com/visgl/react-google-maps/blob/main/examples/geometry/src/components/) by @ArielBenichou for the geometry example can provide a good starting point.

**Comment by usefulthink** [comment]
We can finally close this 🏁  #347

**Comment by chneau** [comment]
Having that just now and it's plenty enough for my usecase:


```ts
import { GoogleMapsContext } from "@vis.gl/react-google-maps";
import { useContext, useEffect, useRef } from "react";

export const Polyline = (props: google.maps.PolylineOptions) => {
	const polyline = useRef(new google.maps.Polyline()).current;
	useEffect(() => {
		polyline.setOptions(props);
	}, [props, polyline.setOptions]);
	const map = useContext(GoogleMapsContext)?.map;
	useEffect(() => {
		map && polyline.setMap(map);
		return () => polyline.setMap(null);
	}, [map, polyline.setMap]);
	return null;
};
```
