### ISSUE TITLE
Support for typescript types

### ISSUE THREAD

**Issue by sosualfred** [visgl/react-google-maps#106]
### Target Use Case

When developing with typescript. It can help with autocomplete and viewing the needed props.

### Proposal

This feature will help make development in typescript easier.

**Comment by usefulthink** [comment]
Not sure what you are referring to, this library was written in typescript and already ships with the .d.ts files needed to enable typing support when using it.

Can you elaborate a bit more what your current setup looks like? Are you seeing any errors?

**Comment by sosualfred** [comment]
I am using NextJs 14 with TypeScript

**Comment by sosualfred** [comment]
It seems to be working now after I run:

`npm i -D @types/google.maps `

**Comment by usefulthink** [comment]
Oooh, that is actually a very good point! Thanks for spotting this.
