### ISSUE TITLE
Can't import the named export 'Children' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by francescocretti** [visgl/react-google-maps#129]
### Description

Hi everyone, I installed the package in my current project and tried to replicate the basic example. At build-time I get the following error:

```
./node_modules/@vis.gl/react-google-maps/dist/index.modern.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)
```

I could be a problem coming from my environment but I wanted to know if anyone has ever encountered something similar.
Thanks in advance.

### Steps to Reproduce

* install `vis.gl/react-google-maps`
* create a simple component

```
const GoogleMapsTest: React.FC = () => {

  return (
    <APIProvider apiKey={API_KEY}>
      <Map
        zoom={3}
        center={{ lat: 22.54992, lng: 0 }}
        gestureHandling={'greedy'}
        disableDefaultUI={true}
      />
    </APIProvider>
  )
}
```
* import it in a route

### Environment

- Library version: `"@vis.gl/react-google-maps": "^0.4.1"`
- Google maps version: weekly
- Browser and Version: Chrome 120
- OS: Mac OSX Ventura - Apple M2 Pro

Dependencies versions (from `package.json`):

```json
"@mapbox/mapbox-gl-draw": "1.3.0",
"react": "17.0.2",
"react-scripts": "4.0.3",
```

**Comment by usefulthink** [comment]
Can you elaborate a bit on your environment? Which bundler or build-steps are you using, how are they configured? Also maybe add the full source-file.

It seems strange that you are loading the `.modern.js` version, but apparently from a commonJS context (which should use the `.umd.js`).

**Comment by francescocretti** [comment]
Hi @usefulthink thanks for your reply.
I'm working on a pre-existent React app made a couple years ago with CreateReactApp.
So it uses webpack under the hood and all the bundling is managed through `react-scripts` and I don't have access to the source code unless I eject from CRA (I really don't want to do it :) ).

I'm trying the road to upgrade to `react-scripts v5`, that seems to be working.

I have other bundling issues now, but I don't think they have anything to do with this package.

I'll keep this issue posted as soon I figured a working solution!

**Comment by usefulthink** [comment]
That's really valuable for us to know, thanks!

**Comment by francescocretti** [comment]
Hi @usefulthink, I can confirm that with `react-scripts` `v5` it works!

**Comment by usefulthink** [comment]
Thanks for the info! I think as create-react-app v5 has been published 2 years ago, we can ignore this for now.

**Comment by fkoessler** [comment]
A note for any future visitor that experiences the described issue: you can bypass the error by importing from the dist folder. For example:

`import { useMapsLibrary } from '@vis.gl/react-google-maps/dist/index.umd'`

**Comment by shuiyuhang** [comment]
> A note for any future visitor that experiences the described issue: you can bypass the error by importing from the dist folder. For example:
> 
> `import { useMapsLibrary } from '@vis.gl/react-google-maps/dist/index.umd'`

What should be done after the introduction? I called useMapsLibrary() in my component to structure APIProvider, Map, etc., but a new error occurred when rendering the component: Uncaught TypeError: Cannot destructure property 'APIProvider' of 'Object(...)(...)' as it is null.

**Comment by shuiyuhang** [comment]
> A note for any future visitor that experiences the described issue: you can bypass the error by importing from the dist folder. For example:
> 
> `import { useMapsLibrary } from '@vis.gl/react-google-maps/dist/index.umd'`


I follow the demo code in the official documentation as follows：
<APIProvider apiKey={"MY_API_KEY"} onLoad={() => console.log("Maps API has loaded.")}>
        <Map
          defaultZoom={13}
          defaultCenter={{ lat: -33.860664, lng: 151.208138 }}
          onCameraChanged={(ev: MapCameraChangedEvent) => console.log("camera changed:", ev.detail.center, "zoom:", ev.detail.zoom)}
        ></Map>
      </APIProvider>

**Comment by sulman45** [comment]
I am having this issue on my react app. I have 
react version 16.14.0 
react scripts version 5.0.1 
googlemap version 3.0
Webpack version 4.42.0
but still it is giving me this error 
ERROR in ./node_modules/@vis.gl/react-google-maps/dist/index.modern.mjs 1554:30-38
Can't import the named export 'useState' from non EcmaScript module (only default export is available)
if i add in webpack config 
{
  test: /\.mjs$/,
  include: /node_modules/,  
type: "javascript/auto",  use: [
    'babel-loader',
  ]
}
its works but adding node modules in webpack will make bundle massively heavy.
So for above configurations i am unable to use this library. Please fix this issue as soon as possible.

**Comment by sulman45** [comment]
> A note for any future visitor that experiences the described issue: you can bypass the error by importing from the dist folder. For example:
> 
> `import { useMapsLibrary } from '@vis.gl/react-google-maps/dist/index.umd'`

**Comment by mrMetalWood** [comment]
@sulman45 Note that "React Hooks" were introduced with version `16.8`. If you are on version `16.14` that might be the cause of your issue. For that reason this library also requires at least version `16.8` to work properly.
