### ISSUE TITLE
initial markers stay on map forever

### ISSUE THREAD

**Issue by plumdumpling** [visgl/react-google-maps#14]
I used the `Marker` component to create some markers on the map. If I remove (or change the properties of) my `<Marker />`s, the initial markers stay on the map.

Here's an example:
https://codesandbox.io/s/pensive-frog-fgztdc?file=/src/index.js
If you click the "move marker" button in the example, you can see that the initial marker at `{lat: 0, lng: 0}` stays on the map.
If you click again, the previous marker is removed correctly.

**Comment by usefulthink** [comment]
Oh, that's clearly a bug :) It doesn't happen when using Advanced markers. Has to be somehow related to this code:
