### ISSUE TITLE
Map is not draggable using NextJS [Bug]

### ISSUE THREAD

**Issue by aagerblad** [visgl/react-google-maps#214]
### Description

I'm trying to set up the simple example in a NextJS environment, but the map isn't draggable.
Cloning the simple example with vite works, but I cannot get it to work with Next.

### Steps to Reproduce

Code sandbox: https://codesandbox.io/p/devbox/f5mzxf

This is minimal next setup, showing the map. The map is not draggable even though the same configuration in vite leads to a draggable map.

### Environment

- Library version: 0.6.0
- Google maps version: weekly
- Browser and Version: Chrome 121.0.6167.139
- OS: Mac Sonoma 14.3

**Comment by usefulthink** [comment]
Since v0.6 we switched to the same pattern react uses for controlled vs uncontrolled props. So if you want an uncontrolled map, you have to change `center` to `defaultCenter` and `zoom` to `defaultZoom`.

Could it be that the vite version you mentioned is still using an older version of this library?

**Comment by aagerblad** [comment]
Yes, that's exactly right, thank you! The examples should probably be updated to reflect this

**Comment by usefulthink** [comment]
I thought we updated all examples, which one are you referring to?

**Comment by usefulthink** [comment]
nevermind, saw it ;)

**Comment by aagerblad** [comment]
It was this one https://github.com/visgl/react-google-maps/blob/main/examples/basic-map/src/app.tsx
but it seems like it was updated between me downloading it (Wednesday) and me posting the issue (Friday).
