### ISSUE TITLE
useMap() is always returning null for me.

### ISSUE THREAD

**Issue by fzkhan19** [visgl/react-google-maps#249]
### Description

I have it wrapped under the APIProvider as well.
This is where I have used it

```
// LocationSearchInput.js
import { useMap, useMapsLibrary } from "@vis.gl/react-google-maps";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Loader from "../Loader/Loader";
import { Input } from "../ui/input";
import { Label } from "../ui/label";

interface Props {
  onPlaceSelect: (place: google.maps.places.PlaceResult | null) => void;
  onChange: (_place: string | null) => void;
  value: string;
}

const mockPredictionResults = [
  {
    description: "Heathrow Airport (LHR), Hounslow, UK",
    place_id: "ChIJ6W3FzTRydkgRZ0H2Q1VT548",
  },
  {
    description: "Gatwick Airport (LGW), Crawley, UK",
    place_id: "ChIJK3mqp_lcX0gRrFtuiPUYr4Q",
  },
  {
    description: "Stansted Airport (STN), Stansted Mountfitchet, UK",
    place_id: "ChIJsyo6rpeb2EcRmUN8o6DfeAo",
  },
  {
    description: "Luton Airport (LTN), Luton, UK",
    place_id: "ChIJFbVSR_ePd0gRCHHv3E31DAo",
  },
  {
    description: "London City Airport (LCY), London, UK",
    place_id: "ChIJx74DkMMEdkgR22kJTzoy3QQ",
  },
];

const LocationSearchInput = ({ onChange, value, onPlaceSelect }: Props) => {
  const map = useMap();
  const places = useMapsLibrary("places");
  const [open, setOpen] = useState(true);
  const [loading, setLoading] = useState(false);

  const [inputValue, setInputValue] = useState<string>("");

  const [sessionToken, setSessionToken] =
    useState<google.maps.places.AutocompleteSessionToken>();

  const [autocompleteService, setAutocompleteService] =
    useState<google.maps.places.AutocompleteService | null>(null);

  const [placesService, setPlacesService] =
    useState<google.maps.places.PlacesService | null>(null);

  const [predictionResults, setPredictionResults] = useState<
    Array<google.maps.places.AutocompletePrediction>
  >([]);

  useEffect(() => {
    if (!places) return;

    setAutocompleteService(new places.AutocompleteService());
    setPlacesService(new places.PlacesService(map));
    setSessionToken(new places.AutocompleteSessionToken());

    return () => setAutocompleteService(null);
  }, [places]);

  const fetchPredictions = useCallback(
    async (inputValue: string) => {
      if (!autocompleteService || !inputValue) {
        setPredictionResults([]);
        return;
      }

      const request = { input: inputValue, sessionToken };
      const response = await autocompleteService.getPlacePredictions(request);
      setPredictionResults(response.predictions);
    },
    [autocompleteService, sessionToken]
  );

  const onInputChange = useCallback(
    (event: FormEvent<HTMLInputElement>) => {
      const value = (event.target as HTMLInputElement)?.value;
      setOpen(true);
      setInputValue(value);
      fetchPredictions(value);
    },
    [fetchPredictions]
  );

  const handleTestClick = (description: string) => {
    console.log("clicked");
    setInputValue(description);
    onChange(description);
    setOpen(false);
  };

  const handleSuggestionClick = useCallback(
    (placeId: string) => {
      if (!places) return;

      const detailRequestOptions = {
        placeId,
        fields: ["geometry", "name", "formatted_address"],
        sessionToken,
      };

      const detailsRequestCallback = (
        placeDetails: google.maps.places.PlaceResult | null
      ) => {
        onPlaceSelect(placeDetails);
        setPredictionResults([]);
        setInputValue(placeDetails?.formatted_address ?? "");
        setSessionToken(new places.AutocompleteSessionToken());
      };

      placesService?.getDetails(detailRequestOptions, detailsRequestCallback);
    },
    [onPlaceSelect, places, placesService, sessionToken]
  );

  const listView = useMemo(() => {
    if (open) {
      if (loading) {
        return <Loader />;
      } else if (inputValue.length > 0) {
        return (
          <ul className="border rounded-lg flex flex-col absolute top-12 z-10 bg-white ">
            {!!predictionResults.length ? (
              predictionResults.map(({ place_id, description }) => (
                <li
                  className="hover:bg-accent p-2 py-4 rounded-md text-sm cursor-pointer"
                  key={place_id}
                  onClick={() => handleSuggestionClick(place_id)}
                  // onClick={() => handleTestClick(description)}
                >
                  {description}
                </li>
              ))
            ) : (
              <Label className="text-sm py-8 text-center">
                No results found
              </Label>
            )}
          </ul>
        );
      }
    }
  }, [loading, handleSuggestionClick, predictionResults, inputValue, open]);

  return (
    <div className="flex flex-col gap-2 relative">
      <Input
        placeholder={`Search Location`}
        onInput={(event: FormEvent<HTMLInputElement>) => onInputChange(event)}
        // value={inputValue}
      />
      {listView}
    </div>
  );
};

export default LocationSearchInput;

``` 

And the APIProvider resides in MapsProvider:

```
import MapsProvider from "@/Providers/MapsProvider";
import Footer from "@/components/Footer";
import CustomHeader from "@/components/Header";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en" className="h-full overflow-hidden">
      <body
        className={cn(
          "flex flex-col h-screen bg-background font-sans antialiased text-bodyFont overflow-auto",
          inter.className
        )}
      >
        <MapsProvider>
          <CustomHeader />
          <div className="grow p-8">{children}</div>
          <Footer />
        </MapsProvider>
      </body>
    </html>
  );
}

```

### Steps to Reproduce

Startup a next.js app wrap the app layout with api provider and use useMaps() underneath that

### Environment

- Library version: "@vis.gl/react-google-maps": "^0.7.1"
- Google maps version: weekly
- Browser and Version: Microsoft Edge
- OS: Windows

**Comment by mrMetalWood** [comment]
Hi @fzkhan19, thanks for reporting your issue.

I tried to reproduce the bug an set up a basic NextJS app on stackblitz. It seems to be working as expected for me. [https://stackblitz.com/edit/stackblitz-starters-mqre3k?file=app%2Fpage.tsx](https://stackblitz.com/edit/stackblitz-starters-mqre3k?file=app%2Fpage.tsx)

Could you try to provide a minimal example where the bug happens so we can investigate what might be going wrong there to cause this?

**Comment by FKonyali** [comment]
I thought it was used in a single component. When I create a new component and use useMap in it, null does not appear. Thank you @mrMetalWood 

I think the ticket opened as a bug may be returning null due to this problem.

**Comment by mrMetalWood** [comment]
@fzkhan19 #250 could the same problem. Where is you `LocationSearchInput ` component used exactly?

**Comment by mrMetalWood** [comment]
Weird. Could you show how you setup the `<APIProvider>` and the `Map` component?

**Comment by fzkhan19** [comment]
App.tsx:
```
"use client";
import HomePageContent from "@/components/HomePageContent";
import InputArray from "@/components/InputArray";
import { useMap } from "@vis.gl/react-google-maps";

export default function Home() {
  const map = useMap();
  console.log(map);
  return (
    <main className="flex min-h-screen gap-4">
      <div className="grow sticky top-24 h-fit">
        <InputArray />
      </div>

      <div className="hidden md:flex flex-col md:w-2/5">
        <HomePageContent />
      </div>
    </main>
  );
}
```
Layout.tsx:
```
import MapsProvider from "@/Providers/MapsProvider";
import Footer from "@/components/Footer";
import CustomHeader from "@/components/Header";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en" className="h-full overflow-hidden">
      <body
        className={cn(
          "flex flex-col h-screen bg-background font-sans antialiased text-bodyFont overflow-auto",
          inter.className
        )}
      >
        <MapsProvider>
          <CustomHeader />
          <div className="grow p-8">{children}</div>
          <Footer />
        </MapsProvider>
      </body>
    </html>
  );
}
```
MapsProvider:
```
"use client";
import { APIProvider } from "@vis.gl/react-google-maps";

const API_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY as string;
const MapsProvider = ({ children }: { children: React.ReactNode }) => {
  return <APIProvider apiKey={API_KEY}>{children}</APIProvider>;
};

export default MapsProvider;
```

**Comment by FKonyali** [comment]
I think I understand the problem. You did not use the <Home /> component in <MapProvider> @fzkhan19 

You should use it like this;
`
<MapsProvider>
          <CustomHeader />
          <div className="grow p-8">{children}</div>
          <Footer />
<Home />
        </MapsProvider>
`

**Comment by FKonyali** [comment]
#250 I think it's the same problem @mrMetalWood

**Comment by fzkhan19** [comment]
@FKonyali Can you explain why is this happening? and wouldn't LocationSearchInput be considered a child element?

**Comment by FKonyali** [comment]
I think it's because we use the "ApiProvider" component. When ApiProvider is defined as a container, it is necessary to define a new component and use the useMap there, and this new component must be added inside the ApiProvider. 

It should be used as in the example usage in the document. I missed it too
[https://visgl.github.io/react-google-maps/docs/api-reference/hooks/use-map](useMap usage)

**Comment by fzkhan19** [comment]
Aaah i see, i missed that lol, but that's kinda weird ngl, but i still don't get why we have to do so with useMap() specifically

**Comment by FKonyali** [comment]
Actually, this is about the functioning of next.js and react.js. I have also experienced this problem in other libraries that require providers(i18n, emotion). If you want to access these hooks within the provider-defined component, I always had problems. I think react.js wants us to use it this way 😄

**Comment by fzkhan19** [comment]
Primagen throwing hate on javascript is justified lol

**Comment by mrMetalWood** [comment]
Hm, from what I'm seeing it should work though I think 🤔 The only thing I don't see anywhere in your code snippets is an actual `<Map>` component. Just making sure.. Do you have a map somewhere in your app?

**Comment by fzkhan19** [comment]
> Hm, from what I'm seeing it should work though I think 🤔 The only thing I don't see anywhere in your code snippets is an actual `<Map>` component. Just making sure.. Do you have a map somewhere in your app?

Nope i'm not using a map anywhere

**Comment by fzkhan19** [comment]
It works now, I added in a <Map> component in the app.tsx, but i really dont have any need for a map, just need a places autocomplete and the coordinates for that place when i click on that, i got the first part figured out, just selecting the place part is pending

**Comment by mrMetalWood** [comment]
As far as I can see you want to pass the map to the Places service. You can also pass it a HTML element for rendering of possible attributions. Then you don't even need a map.

[https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacesService.constructor](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacesService.constructor)

**Comment by fzkhan19** [comment]
ahh now that solves the issue thanks, i'll try that

**Comment by Felixmurithi** [comment]
Found myself debgging a similar issue where the APILibrary I was calling always returned a null value. I think the docs should be improved to make it clear that the APIProvider is supposed to be a parent of the component where those hooks are called.

**Comment by usefulthink** [comment]
@Felixmurithi do you have a suggestion where and how this could best be done? I could see that as a remark somewhere in the README (maybe add another shoer example below the first example about the hooks?) and also as an admonition in the API docs for the hooks.

Would you like to open a PR to add this?

**Comment by Felixmurithi** [comment]
> @Felixmurithi do you have a suggestion where and how this could best be done? I could see that as a remark somewhere in the README (maybe add another shoer example below the first example about the hooks?) and also as an admonition in the API docs for the hooks.
> 
> Would you like to open a PR to add this?

I will open a PR for this, I think adding another example would be the best way to do it.

**Comment by pnavk** [comment]
Per @mrMetalWood, this is the fix if you don't want to render a map and just use the service
> As far as I can see you want to pass the map to the Places service. You can also pass it a HTML element instead for rendering of possible attributions. Then you don't even need a map.
> 
> https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacesService.constructor

Instead of passing in the return value of `useMap()` you can pass in a ref to an element:

This works for me:
```
function Component() {
  const placesLibrary = useMapsLibrary("places");
  const [placesService, setPlacesService] = useState<google.maps.places.PlacesService | null>(null);
  const attributionElementRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!placesLibrary || !attributionElementRef.current) return;
    setPlacesService(new placesLibrary.PlacesService(attributionElementRef.current));
  }, [placesLibrary]);

  <>
    {/* other components */}
    <div ref={attributionElementRef} />
  </>;
}
```

**Comment by AlenMartinez** [comment]
### I had the same issue where **useMap()** was always returning **null**.

**Just to clarify**: in my case, I used useMap() inside a component that has no direct relation to the one where the <Map /> is rendered. I'm just sharing how it worked for me — your structure might differ, but the pattern can still help.

Here's what I did:

**In one component (let's call it Component A, which uses Google Place and does not render the <Map />), I call:**

`const map = useMap('map_id'); // 'map_id' can be any string`

**Then, in another component (e.g., Component B, which is not a parent or child of A), I render the map like this:**

`<Map id="map_id"  .......your props......../>`

And that’s it — it worked perfectly.
