### ISSUE TITLE
[Bug] Cannot display the component more than once on the same page

### ISSUE THREAD

**Issue by gregbzh** [visgl/react-google-maps#255]
### Description

It seems that the component can only be displayed once on a page. Adding multiple time will render an empty map container.

### Steps to Reproduce

Create a map component 

 ```
const MyMap = () => {
  const center = { lat: 46.2044, lng: 6.1432 };
  const zoom = 12;
  return (
      <APIProvider apiKey={'API_KEY'}>
        <GoogleMap defaultCenter={center} defaultZoom={10}>
          <Marker position={center} />
        </GoogleMap>
      </APIProvider>
)}
 ```

Add multiple MyMap components to a page.

 ```
const MyApp = () => {
 return (
      <>
        <MyMap />
        <MyMap />
      </>
)}
 ```

 The map will render only once. This behaviour does not appear with other lib like https://github.com/googlemaps/react-wrapper

### Environment

- Library version:
- Google maps version: weekly
- Browser and Version:
- OS:

**Comment by mrMetalWood** [comment]
Hi @gregbzh. It could be because you have multiple `APIProvider` components. Can you try to only load the api once for your app?

Like this for example: 
```
const MyMap = () => {
 const center = { lat: 46.2044, lng: 6.1432 };
 const zoom = 12;
 return (
     <GoogleMap defaultCenter={center} defaultZoom={10}>
       <Marker position={center} />
     </GoogleMap>
)}
```

```
const MyApp = () => {
return (
     <APIProvider apiKey={'API_KEY'}>
       <MyMap />
       <MyMap />
     <APIProvider/>
)}
```

**Comment by gregbzh** [comment]
Hi, good catch, that was the issue. Thanks !
