### ISSUE TITLE
Setting zoom is not animated

### ISSUE THREAD

**Issue by gregbzh** [visgl/react-google-maps#259]
### Description

Using both approaches, zoom state or useMap().setZoom, the zoom is well set but it seems that we lost the zoom animation and I cannot find a way to do it.

### Steps to Reproduce

Create a Map and change the zoom by a controlled state value or by using useMap().setZoom

### Environment

- Library version:
- Google maps version: weekly
- Browser and Version:
- OS:

**Comment by usefulthink** [comment]
I think there's nothing for us to do here. Please reopen, or open a discussion for questions about how to best animate the google maps camera-parameters. Having easily accessible Camera Animations is definitely something we should evaluate at some point.
