### ISSUE TITLE
[Bug] Drawing tools will be created for every call on useDrawingTools

### ISSUE THREAD

**Issue by RHeynsZa** [visgl/react-google-maps#260]
### Description

![image](https://github.com/visgl/react-google-maps/assets/58415372/b52a7c7a-9e1e-4ded-8643-ae48c57248fa)

Any rerender of the Map component, or call on useDrawingManager, will cause a new instance of the drawing tools to appear

### Steps to Reproduce

Call useDrawingManager more than once, and see the multiple drawing tools 

### Environment

- Library version: 0.7.0
- Google maps version: weekly
- Browser and Version: Brave
- OS: Windows

**Comment by mrMetalWood** [comment]
Hi @RHeynsZa. Thanks for reporting this issue.
Adding a cleanup function to the `useEffect` in the `useDrawingManager` example hooks should do the trick. I issued a PR to implement that in the example. https://github.com/visgl/react-google-maps/pull/262/files

**Comment by ahsan-epacken** [comment]
Have same issue still 

version :
`  "@vis.gl/react-google-maps": "^0.7.1"`


`import { useMap, useMapsLibrary } from '@vis.gl/react-google-maps';
import { useEffect, useState } from 'react';

export function useDrawingManager(
  initialValue: google.maps.drawing.DrawingManager | null = null,
) {
  const map = useMap();
  const drawing = useMapsLibrary('drawing');

  const [drawingManager, setDrawingManager] =
    useState<google.maps.drawing.DrawingManager | null>(initialValue);

  useEffect(() => {
    if (!map || !drawing) return;
    const newDrawingManager = new drawing.DrawingManager({
      map,
      drawingControl: true,
      drawingControlOptions: {
        position: google.maps.ControlPosition.TOP_CENTER,
        drawingModes: [
          google.maps.drawing.OverlayType.MARKER,
          google.maps.drawing.OverlayType.CIRCLE,
          google.maps.drawing.OverlayType.POLYGON,
          google.maps.drawing.OverlayType.POLYLINE,
          google.maps.drawing.OverlayType.RECTANGLE,
        ],
      },
      markerOptions: {
        draggable: true,
      },
      circleOptions: {
        editable: true,
      },
      polygonOptions: {
        editable: true,
        draggable: true,
      },
      rectangleOptions: {
        editable: true,
        draggable: true,
      },
      polylineOptions: {
        editable: true,
        draggable: true,
      },
    });

    setDrawingManager(newDrawingManager);

    return () => {
      newDrawingManager.setMap(null);
    };
  }, [drawing, map]);

  return drawingManager;
}
`

**Comment by mrMetalWood** [comment]
@ahsan-epacken can you share how exactly you are using the `useDrawingManager` hook? Or even better, create a minimal complete example where that happens for you? That would help a lot.
