### ISSUE TITLE
useTrackedCameraState error

### ISSUE THREAD

**Issue by shamsanjay156** [visgl/react-google-maps#263]
### Description

im Getting ith error while loading the map

**[useTrackedCameraState] at least one of the values from the map returned undefined. This is not expected to happen. Please report an issue at**

### Steps to Reproduce

try in Code Sandbox

### Environment

- Library version:
- Google maps version: weekly
- Browser and Version:
- OS:

**Comment by usefulthink** [comment]
Interesting, can you add a bit more info about the circumstances when that happens? Is that happening consistently for you?

**Comment by shamsanjay156** [comment]
Hi @usefulthink and other folks!
Sorry for raising this bug, Mistake is mine I forgot to give a required **center/default center** and **zoom/default zoom** props
