### ISSUE TITLE
[Feat] Security Proxy

### ISSUE THREAD

**Issue by TheCardinalSystem** [visgl/react-google-maps#275]
### Target Use Case

Currently, this project's `APIProvider` only supports direct a API connection using an API key. However, if I am to make a public web app which uses this package, I do not want to expose my API key on the frontend.

### Proposal

Allow the `APIProvider` component to support proxying all API requests to the backend server where the API key can be appended and then forwarded to the requested target.

**Comment by usefulthink** [comment]
I'm not sure this would actually work for the Maps JavaScript API.

First off, exposing the maps api-key publicly is [the only officially supported way](https://developers.google.com/maps/documentation/javascript/load-maps-js-api) of using the Google Maps JavaScript API. I have never seen any application redirecting the requests via a proxy like you suggest and I would be curious to hear more about the need for this.

As far as I know, the validation of the key has to happen on the client (and possibly only on the client). The API will, after initially bootstrapping (and before actually rendering the map), send a validation-request containing the API-key and the current URL to an API server. If this request doesn't contain the API-key, an error-message will be shown, the map will not show or both (I'm not sure what exactly would happen in this case).

**Comment by TheCardinalSystem** [comment]
Well this is certainly curious. What is to prevent someone from stealing my API key and using it for his own purposes? The key is linked to my billing profile, so having it used by an unauthorized party could incur charges on my Google account. That is my current understanding, anyway. Am I misunderstanding the purpose and usage of the key?

**Comment by TheCardinalSystem** [comment]
> I'm not sure this would actually work for the Maps JavaScript API.
> 
> First off, exposing the maps api-key publicly is [the only officially supported way](https://developers.google.com/maps/documentation/javascript/load-maps-js-api) of using the Google Maps JavaScript API. I have never seen any application redirecting the requests via a proxy like you suggest and I would be curious to hear more about the need for this.
> 
> As far as I know, the validation of the key has to happen on the client (and possibly only on the client). The API will, after initially bootstrapping (and before actually rendering the map), send a validation-request containing the API-key and the current URL to an API server. If this request doesn't contain the API-key, an error-message will be shown, the map will not show or both (I'm not sure what exactly would happen in this case).

Well this is certainly curious. What is to prevent someone from stealing my API key and using it for his own purposes? The key is linked to my billing profile, so having it used by an unauthorized party could incur charges on my Google account. That is my current understanding, anyway. Am I misunderstanding the purpose and usage of the key?

**Comment by usefulthink** [comment]
Understood. 

The way we've been handling this in almost all cases was by restricting the keys to a limited set of URLs and
limiting the APIs enabled for that key to a minimal set of required APIs.

Additionally, you can you can create quotas for API usage and set up alerts and project-wide limits with regards to the money spent.

Also see the official [security best-practices](https://developers.google.com/maps/api-security-best-practices).

**Comment by usefulthink** [comment]
I'm closing this since there doesn't seem to be anything to be done here. Please reopen if you want to discuss this further.

**Comment by ticmaisdev** [comment]
This would be great a feature, since URL restriction **can be bypassed** or even a simple bug on the client side could cause huge bill.

Other than that, there's more advantages that comes with proxying like **user authentication**, **audience restriction**, **throttling** and **caching**.

From my end, I've successfully implemented all these features thanks to proxying. I'm using `pnpm patch` as of now, but it would be nicer to have a native way to set hostname.

**Comment by usefulthink** [comment]
> [...] URL restriction can be bypassed or even a simple bug on the client side could cause a huge bill.

That is true, but in practice I rarely saw stolen API keys being used maliciously. What I've seen far more often is careless use of APIs, bugs etc. racking up cost – a proxy isn't going to help with that.
Also, you can (and probably should) set up alerts, spending limits and quotas for the maps API to prevent that from ever being a problem. 

This whole topic of configuring the API keys and security considerations is something I would like to add to our documentation when I find the time.

> Other than that, there's more advantages that comes with proxying like user authentication, audience restriction, throttling and caching.

I agree with all of these points. Just wanted to add that the ToS explicitly forbids caching. 

> From my end, I've successfully implemented all these features thanks to proxying. I'm using pnpm patch as of now, but it would be nicer to have a native way to set hostname.

Can you share a bit more about how this works with the Maps JavaScript API? Can you actually render a map while loading the entire JS through a proxy?

> Proxying is also 1 of the recommended ways to [protect API keys in apps using web services](https://developers.google.com/maps/api-security-best-practices#mobile-ws-static-web).

This is referring to the Data-APIs and not the Maps JavaScript API.
