### ISSUE TITLE
[Bug] Adding <MapControl /> to a <GoogleMap /> with invalid/expired key make component crash

### ISSUE THREAD

**Issue by gregbzh** [visgl/react-google-maps#276]
### Description

When GoogleMap component contains a MapControl and APIProvider key is invalid or expired, the app crash.

In https://github.com/visgl/react-google-maps/blob/750acb981f5c250fbc6fea3fda59cdf8eb00f60d/src/components/map-control.tsx#L61

indexOf is crashing if controls.getArray() is undefined.

### Steps to Reproduce

Create a GoogleMap containing a MapControl with an expired api key.

### Environment

- Library version:
- Google maps version: weekly
- Browser and Version:
- OS:

**Comment by usefulthink** [comment]
Thanks for reporting! It seems we got fooled by the @types/google.maps types, there it states that controls.getArray() will always return an array.

But I think we just need to add a check there and should be fine.
