### ISSUE TITLE
[Bug] missing center/zoom props don't produce an error or warning

### ISSUE THREAD

**Issue by usefulthink** [visgl/react-google-maps#283]
### Description

When the center/zoom properties aren't set, the map can't render which can cause all sorts of problems. We should handle this somehow, for example by logging a warning to the console.

### Steps to Reproduce

no

### Environment

- Library version: 0.8.x
- Google maps version: any
- Browser and Version: all
- OS: all

**Comment by BParvatkar** [comment]
Can we have a logic where if both zoom and defaultZoom aren't defined then we have a default value of defaultZoom that gets applied to the map?

**Comment by usefulthink** [comment]
@BParvatkar I would like that as well, but it's difficult to pick a value not knowing what you're up to (world-map or city-map?). 

Maybe issuing a warning and defaulting to rendering a world-map combine to be the best developer experience.

**Comment by maciej-ka** [comment]
How about geolocation as a failback? (which can be denied, in which case we would need failback for failback, hmmm)

**Comment by usefulthink** [comment]
No, that'd be way too intrusive.
