### ISSUE TITLE
[Bug] any component using the useMap hook gets rerendered anytime the map is panned/zoomed

### ISSUE THREAD

**Issue by mfavetti** [visgl/react-google-maps#285]
### Description

a component that is a child of a map and calls the useMap hook gets rerendered anytime the map is panned or zoomed

### Steps to Reproduce

create an app like

APIProvider -> Map -> SomeComponent

within SomeComponent, call useMap

run the app, pan/zoom the map

Minimal example:
```
import React from 'react'
import ReactDOM from 'react-dom/client'
import { APIProvider, Map, useMap } from '@vis.gl/react-google-maps';

const API_KEY = '';
const MAP_ID = '';

const Test = (props) => {
  const map = useMap();

  console.log(`rerender!!!!!!!`);
}

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <APIProvider apiKey={API_KEY}>
      <Map
        style={{height: '500px'}}
        defaultCenter={{lat: 36.7783, lng: -119.4179}} // california
        defaultZoom={6}
        mapId={MAP_ID}
        gestureHandling={'greedy'}
        disableDefaultUI={true}
        >
        <Test />
      </Map>
    </APIProvider>
  </React.StrictMode>,
)
```

comment out the useMap line and the issue is gone. doesn't really affect this example but if the component deals with rendering thousands of markers or something like that, it's unusable

### Environment

- Library version: 0.8.1
- Google maps version: weekly 3.56.6
- Browser and Version: Chrome 122.0.6261.57
- OS: Mint 21.3 Cinnamon

**Comment by mfavetti** [comment]
maybe this just isn't intended use case...
i got around it by rendering the markers separately and then just sending their refs to the other code
but maybe there should be something in the docs?

curious to hear your thoughts

**Comment by usefulthink** [comment]
That's an interesting one, and not so obvious to see, so thanks for spotting and reporting this! 
Obviously, we don't want to cause excessive re-renders when they're not actually needed, so we have to come up with a solution for this.

**Comment by usefulthink** [comment]
I feel like this is could be related to all sorts of problems experienced by others as well. So, thanks again for spotting it. Fix will land and release shortly.
