### ISSUE TITLE
[Feat] Rendering multiple maps in different locations on the same page

### ISSUE THREAD

**Issue by LouayJebran** [visgl/react-google-maps#295]
### Target Use Case

We are currently working on the development of a website using ASP.NET
featuring custom modules implemented in React, .NET Components, etc
One of them is a custom map React component built with your package.

Here's an example of the website structure:

```
<!DOCTYPE html>
<html>
<body>

@await Html.PartialAsync("customModule");

@* our custom map react component *@
<div id="customMapReactModule">
</div>

@await Html.PartialAsync("anotherCustomModule");

<div id="anotherReactModule">
</div>

@* another instance of the react component *@
<div id="customMapReactModule">
</div>

</body>
</html>

```

Initially, everything worked fine, but we encountered an issue with this package where only the first map would be rendered. As I understand it, the map module can only be rendered within an APIProvider. Multiple maps must be rendered under the same APIProvider.

Unfortunately, this doesn't work in our use case since some pages could include more than one map in a different order.

### Proposal

The ideal scenario, if possible, is to render each map as a separate React component .

for instance, our react component looks as the following

```
return (
<APIProvider apiKey={APIKEY}>
       <div class="...">
              <Map mapId="MAPID">
                    <CustomMarkers />
              </Map>
       </div>
</APIProvider >
);
```
We would like to able to inject it anywhere on the page 
to render a map with, for example, different settings and custom features.

**Comment by LouayJebran** [comment]
The Problem seems to be that any APIProviders added after the initial one gets stuck in the Loading state

The first one is loaded and works fine
![Works](https://github.com/visgl/react-google-maps/assets/54023757/6e37ea38-8563-4147-b4c7-2d18c79b09d0)

second one stuck during loading
![StuckInLoading](https://github.com/visgl/react-google-maps/assets/54023757/e209f522-f3ac-420c-befb-1f83222baafc)

**Comment by LouayJebran** [comment]
hi @usefulthink
yes you got this right, we have multiple React render-roots in the same page.
thanks for taking the time to check if it's a bug.

not sure if this could help in any way 
tinkering with the react dev tools and setting the state of GoogleMapsApiLoader to "LOADED" like the first instance of the APIProvider seem to load the second map

![image](https://github.com/visgl/react-google-maps/assets/54023757/2c251c5a-d326-40e6-b9f2-c80b4f787141)

**Comment by usefulthink** [comment]
I just made a new release 0.8.3 which should in theory solve the problem you've been seeing. 
At least I did find and fix a bug in our API loader that would explain the status of the second APIProvider not getting updated. 

There might be other issues with your setup (nobody thought of having multiple react-roots in the same page), but please let me know once you tested it.

**Comment by LouayJebran** [comment]
@usefulthink 
Just tested it, and it seems to be working great.
thanks again and I will keep an eye for any problem that may arise in our setup.

**Comment by usefulthink** [comment]
Awesome, thanks for letting me know!
