### ISSUE TITLE
[Feat] Add example of how to use controlled map with mouse drag

### ISSUE THREAD

**Issue by wilson-nickolas** [visgl/react-google-maps#296]
### Target Use Case

Learning / Documentation.

### Proposal

There is no example of controlled map usage that shows how to correctly use the library with mouse drag events. So it would be helpful to many people to see how this is correctly done.

**Comment by usefulthink** [comment]
We have an example with fully controlled maps here: https://visgl.github.io/react-google-maps/examples/multiple-maps

Is that what you're looking for or am I misunderstanding?

**Comment by wilson-nickolas** [comment]
@usefulthink 
Thanks for the link. I just took a quick look over it and it seems to confirm what I had setup. So perhaps I should be making a bug issue. Basically, I'm experiencing no new camera movements from mouse events using controlled map.

**Comment by wilson-nickolas** [comment]
> Please do! The deck.gl integration (when using deck as controlling component) has a slightly different code-path, might be we missed something around there.

Cheers, I do that then first thing tomorrow. Thanks for your help.

**Comment by qiaoxin136** [comment]
I am interested in the same topic. How do i add deck.gl into this controlled map example with multiple synchronous maps? Did you have another example somewhere? Thanks. It is a great work.
