### ISSUE TITLE
<ApiProvider> failed to load Google Maps API Error

### ISSUE THREAD

**Issue by fzkhan19** [visgl/react-google-maps#377]
### Description

<ApiProvider> failed to load Google Maps API Error: The library map is unknown. Please see https://developers.google.com/maps/documentation/javascript/libraries.

 
 GET https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true 
 net::ERR_BLOCKED_BY_CLIENT
﻿
﻿
﻿I'm using next.js 14 app router and the component wrapped in APIProvider is logging this error, the functionality is working well though.

This is the code:

```
"use client";
import {APIProvider} from "@vis.gl/react-google-maps";

const API_KEY = (process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY as string) || "";
const MapsProvider = ({children}: {children: React.ReactNode}) => {
  return (
    <APIProvider apiKey={API_KEY} libraries={["core", "map", "places", "routes"]}>
      {children}
    </APIProvider>
  );
};

export default MapsProvider;
```

### Steps to Reproduce

"use client";
import {APIProvider} from "@vis.gl/react-google-maps";

const API_KEY = (process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY as string) || "";
const MapsProvider = ({children}: {children: React.ReactNode}) => {
  return (
    <APIProvider apiKey={API_KEY} libraries={["core", "map", "places", "routes"]}>
      {children}
    </APIProvider>
  );
};

export default MapsProvider;

The code in question

### Environment

- Library version: ^0.7.1
- Google maps version: weekly
- Browser and Version: Edge
- OS: Windows 11

**Comment by shuuji3** [comment]
Hi, @fzkhan19.

> failed to load Google Maps API Error: The library map is unknown. Please see [developers.google.com/maps/documentation/javascript/libraries](https://developers.google.com/maps/documentation/javascript/libraries).

Maybe this error was caused by the typo (`map`) in the `libraries` list.

But as written in the documentation page in the error message, the supported value is `maps` (not `map`): https://developers.google.com/maps/documentation/javascript/libraries#libraries-for-dynamic-library-import

Would you be able to replace the library name like this?

```diff
-    <APIProvider apiKey={API_KEY} libraries={["core", "map", "places", "routes"]}>
+    <APIProvider apiKey={API_KEY} libraries={["core", "maps", "places", "routes"]}>
```

**Comment by fzkhan19** [comment]
Thanks that worked!
But I'm still getting the
GET https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true net::ERR_BLOCKED_BY_CLIENT

**Comment by usefulthink** [comment]
The `net:ERR_BLOCKED_BY_CLIENT` is a message you get from content blockers like ABP or uBlock Origin.

Also note that you don't have to specify the libraries on load if you don't always need them. You can also use the `useMapsLibrary` hook in the components that need special libraries.

**Comment by fzkhan19** [comment]
got it thanks a lot, it's resolved!🙌
