### ISSUE TITLE
[Feat] Add support for InfoWindow headerContent / headerDisabled options

### ISSUE THREAD

**Issue by usefulthink** [visgl/react-google-maps#378]
### Target Use Case

Currently in beta in the Maps JavaScript API, there will be new options for the InfoWindow, finally allowing users to disable the header including the close-button and to specify separate html for the header of the infowindow. These should be supported here as well.

### Proposal

Add new props `headerContent` and `headerDisabled` for the `InfoWindow` component. While headerDisabled is just a boolean, headerContent can be arbitrary html, so we should support that via a render-callback, rendering the content into a portal.

**Comment by amanusovich** [comment]
Hi,

I noticed this feature is already available in the Maps JavaScript API and currently affecting the components provided here. 

<img width="246" alt="Screenshot 2024-05-28 at 1 03 00 PM" src="https://github.com/visgl/react-google-maps/assets/140748735/f866f104-a3ce-46f0-b675-b71572cea72d">

This is affecting the styling of the component, specially when its content is short. Providing this functionality would really help.

Thank you!

**Comment by usefulthink** [comment]
Currently this only happens with the beta version of the maps API, so we still have a bit of time..

**Comment by amanusovich** [comment]
Actually I am working with the API in the weekly version. I changed it to monthly to get the older version.

Thanks!

**Comment by chrissygonzalez** [comment]
Hello! I'd also like to vote for a little customization. 🙏  Thanks!

![Screenshot 2024-05-29 at 1 22 29 PM](https://github.com/visgl/react-google-maps/assets/8127482/9598577c-116f-49ee-a4ae-7d9267a236f4)

**Comment by kamaladenalhomsi** [comment]
Same here!! I think this is extremely important!
Not related to the issue, I want to thank the maintainers of this awesome library! Thank you for your hard work.

**Comment by kamaladenalhomsi** [comment]
For anyone facing this, you can temporary fix the empty space at the top using css:

```css
.gm-style-iw-chr {
  position: absolute;
  display: flex;
  top: 0;
  right: 0;
}

.gm-style-iw.gm-style-iw-c {
  padding-top: 14px !important;
}
```

**Comment by usefulthink** [comment]
The `headerDisabled` flag should actually work out of the box since it should get passed on to the `google.maps.InfoWindow` constructor and the `infowindow.setOptions()` method. When using typescript you'll have to have the latest `@types/google.maps` installed.

As for `headerContent`, which API-style would be preferrable?

### Option 1: Render callback (`{headerContent: React.ComponentType}`)

```tsx
<InfoWindow headerContent={() => <h3>InfoWindow Headline</h3>}></InfoWindow>
<InfoWindow headerContent={() => <>Just some text</>}></InfoWindow>

<InfoWindow headerContent={MyInfoWindowHeader}></InfoWindow>
```

### Option 2: JSX (`{headerContent: React.ReactNode}`)

```tsx
<InfoWindow headerContent={<h3>InfoWindow Headline</h3>}></InfoWindow>
<InfoWindow headerContent={<MyInfoWindowHeader />}></InfoWindow>
```

### Option 3: Special Child Component

```tsx
<InfoWindow>
  <InfoWindowHeader><h3>InfoWindow Headline</h3></InfoWindowHeader>
  
  <p>Infowindow Content</p>
</InfoWindow>
```

I think I would prefer the second or third option for this. The second option seems to be what other UI libraries are using in similar situations, any opinions here?

**Comment by chrissygonzalez** [comment]
I like option 2, given that `headerDisabled` will be available. (At first I though option 3 was more intuitive, but you could end up in an odd situation if you set `headerDisabled={true}` and then also provided some header content.)

**Comment by usefulthink** [comment]
I'm mostly sceptical about option 3 since that would involve some sort of accessing portals within (or out of?) portals, and I have no Idea if that causes problems, but It's complicated to just think about. I'd be willing to figure it out if majority says that's the better solution, but we'll see...

**Comment by skulas** [comment]
This is what I did, based on messages above in this thread:
`
const infoWnd = new google.maps.InfoWindow({
            content: infoWindowContent,
            maxWidth:200,
 })
 infoWnd.setHeaderDisabled(true)
`
and it fixed my pop-up window.
Thank you.
Wish the world learnt from swr engs how to collaborate...

**Comment by ptbarnum4** [comment]
> .gm-style-iw-chr {
>   position: absolute;
>   display: flex;
>   top: 0;
>   right: 0;
> }


Similar to what @kamaladenalhomsi [is suggesting](https://github.com/visgl/react-google-maps/issues/378#issuecomment-2141560117), you can add the css to the content html string and just fix the header text

```ts
// Create window with styles
const infoWindow = new  InfoWindow({
  content: `
  <style>
    .gm-style-iw-chr {
      color: #222222;
      font-weight: 700;
    }
  </style>
    <div class="iw-content">
      <a
        href="${locationUrl}"
        target="_blank"
      >
        Open in Google Maps
      </a>
    </div>
  `,
});

// Set header content
// Note: The text is initially light font-weight and white
infoWindow.set('headerContent', 'The coolest header');
```

**Comment by phil-hudson** [comment]
FYI you can now use:

```
                <InfoWindow
                    position={{ lat: marker.lat, lng: marker.lng }}
                    onCloseClick={() => setActiveMarker(null)}
                    options={{
                      disableAutoPan: true,
                      pixelOffset: new window.google.maps.Size(0, -40),
                      headerDisabled: true, < disable header
                    }}
                  >
```
