### ISSUE TITLE
Map is not loading properly when using AdvancedMarker

### ISSUE THREAD

**Issue by matomesc** [visgl/react-google-maps#427]
### Description

I'm trying to create a map with some AdvancedMarkers but the map is not loading properly.
<img width="433" alt="chrome_srOBkhC3YT" src="https://github.com/visgl/react-google-maps/assets/477723/92a60b41-1870-4d86-a262-d9bced7d5ecb">

### Steps to Reproduce

Create the following component and render it. It displays the error above.

```tsx
export const Component: React.FC = () => {
  return (
    <APIProvider apiKey={API_KEY} libraries={['marker']}>
      <Map id="map" defaultZoom={15} defaultCenter={{ lat: 29.5, lng: -81.2 }}>
        <AdvancedMarker position={{ lat: 29.5, lng: -81.2 }} />
      </Map>
    </APIProvider>
  );
};
```

### Environment

- Library version: 1.10
- Google maps version: weekly
- Browser and Version: Google Chrome version 126.0.6478.63
- OS: Windows 11

**Comment by usefulthink** [comment]
I believe this will happen when you try to use the AdvancedMarkers on a map that is loaded without a [mapId](https://developers.google.com/maps/documentation/get-map-id).

**Comment by matomesc** [comment]
Fixed by initializing the map with `mapId` prop.

```tsx
export const Component: React.FC = () => {
  return (
    <APIProvider apiKey={API_KEY} libraries={['marker']}>
      <Map mapId="map" defaultZoom={15} defaultCenter={{ lat: 29.5, lng: -81.2 }}>
        <AdvancedMarker position={{ lat: 29.5, lng: -81.2 }} />
      </Map>
    </APIProvider>
  );
};
```

**Comment by Nicolasvegam** [comment]
for me, that was the fix btw
