### ISSUE TITLE
[Bug] Map is not draggable if center props is passed. 

### ISSUE THREAD

**Issue by GulinaTayier** [visgl/react-google-maps#436]
### Description

If I pass center props the map is not draggable

### Steps to Reproduce

Any example code, pass a `center` props to `<Map />` component.

https://codesandbox.io/p/devbox/github/visgl/react-google-maps/tree/main/examples/extended-component-library?file=%2Fsrc%2Fapp.tsx 

https://codesandbox.io/p/devbox/competent-panna-4w83x2?file=%2Fsrc%2Fapp.tsx

Try dragging using the cursor, it doesn't work. 

### Environment

- Library version:
- Google maps version: weekly
- Browser and Version:
- OS:

**Comment by usefulthink** [comment]
If I understand you correctly (I can't open the second link you posted, it says "Devbox not found"), this is working as intended and documented here: https://visgl.github.io/react-google-maps/docs/api-reference/components/map#controlled-and-uncontrolled-props

But we maybe should extend that example a bit to also show how to deal with the controlled props while also allowing user-interaction via the `onCameraChange` events (as per the example in the documentation I posted above).

**Comment by GulinaTayier** [comment]
> If I understand you correctly (I can't open the second link you posted, it says "Devbox not found"), this is working as intended and documented here: https://visgl.github.io/react-google-maps/docs/api-reference/components/map#controlled-and-uncontrolled-props
> 
> But we maybe should extend that example a bit to also show how to deal with the controlled props while also allowing user-interaction via the `onCameraChange` events (as per the example in the documentation I posted above).

Thank you for the quick reply and clarification, appreciate it! And using `onCameraChange` indeed worked. 

What I wanted to accomplish at first was render map and a list of place, user can click on each place on the list and the map will center to that location, at the mean time user could also interact with the map using mouse event. 

Here is my working code
```export const GoogleMap = ({ children, center, defaultZoom }: Props) => {
    const [mapCenter, setMapCenter] =
        useState<google.maps.LatLngLiteral>(DEFAULT_CENTER);

    useEffect(() => {
        if (center) {
            setMapCenter(center);
        }
    }, [center]);

    const handleCameraChange = useCallback((ev: MapCameraChangedEvent) => {
        setMapCenter(ev.detail.center);
    }, []);

    return (
        <Map
            center={mapCenter}
            mapId={config.googleMapId}
            clickableIcons={false}
            gestureHandling="greedy"
            defaultCenter={DEFAULT_CENTER}
            defaultZoom={defaultZoom || DEFAULT_ZOOM}
            mapTypeControl={false}
            streetViewControl={false}
            id="sharedComponentMap"
            reuseMaps={true}
            disableDefaultUI={true}
            onCameraChanged={handleCameraChange}
        >
            {children}
        </Map>
    );
};```
