### ISSUE TITLE
[Bug] When I use the center or zoom props on MapWrapper the map locks the user from controlling those in the UI

### ISSUE THREAD

**Issue by davebrewer** [visgl/react-google-maps#452]
### Description

Great map plugin, have got stuck with trying to set the center and zoom coords for a marker and still give the capability to the user to zoom and drag the map around. Don't seem to be able to find a way to do this and have previously used other google map wrappers that have supported this so wonder if this is a feature / bug or i'm just implementing wrong?

Cheers for any guidance,
Dave

### Steps to Reproduce

Implementing like this, can provide more info if required.

<MapWrapper
    mapId={'map_01'}
    defaultCenter={defaultLocation}
    defaultZoom={defaultZoom}
    zoom={ current?.lat ? 16 : 13}
    center={center}
    controlled={false}
  >

### Environment

- Library version: ^1.1.0
- Google maps version: weekly
- Browser and Version: Chrome
- OS: Mac

**Comment by usefulthink** [comment]
I notice a couple of things here:

 - `mapId`: this is the mapId you can create in the Google Cloud Console when using [Cloud Based Map Styling](https://developers.google.com/maps/documentation/get-map-id) – there's also `id` that you can pass your own values to, but that is only needed if you want to use multiple maps in the same API provider and need to access them with hooks from the outside
 - while it shouldn't cause any problems, `defaultCenter` / `defaultZoom` are obsolete when using the center/zoom props
 - `controlled={false}` is the default value, you can leave that away

As for letting users control the map as usual: if you need the ability to programmatically set center/zoom, you use the center/zoom props, if you don't need that ability, using the default* props is fine. 

What I'm not seeing in your example is handling of the `onCameraChanged` event. The way this is supposed to work is something like this:

```tsx
const INITIAL_CAMERA_PROPS = {
  center: {lat: 10, lng: 20},
  zoom: 5,
  heading: 0, 
  tilt: 0
};

const MyMap = () => {
  const [cameraProps, setCameraProps] = useState(INITIAL_CAMERA_PROPS);
  const handleCameraChange = useCallback((ev: CameraChangedEvent) => { setCameraProps(ev.detail); }, []);

  // here, you can use setCameraProps() to update the maps virtual camera to whatever position you 
  // like and the user will still be able to navigate.

  return <Map {...cameraProps} onCameraChanged={handleCameraChange}></Map>
}
```

**Comment by usefulthink** [comment]
Not yet, so you'd have to implement them manually (for example using the useMap/useEffect hooks).

I think that would be a great addition to this library, but I haven't yet found a good "react-ish" way to implement them. If you have some examples how it's done in other libraries and other contexts, I'd love to see it!

**Comment by davebrewer** [comment]
Seemed to work out of the box on this one but haven't delved too much under the hood tbh:
https://www.npmjs.com/package/google-map-react

Hope it helps!

**Comment by Felixmurithi** [comment]
In case u run into this issue the best way to do it is to

`        onCameraChanged={() => setCenter()}
`
U can set the center as you like in other events, which will be immediately overridden on camera change.

Changing the center everytime the camera is changed is very slow. 

U can also rename this issue to a more descriptive title  i.e map center cannot be controlled/change once the center prop is set
