### ISSUE TITLE
[Bug] problem when addint two or more ImageMapType Layers

### ISSUE THREAD

**Issue by ufoloko** [visgl/react-google-maps#457]
### Description

If you add 2 or more layers of type **window.google.maps.ImageMapType** on map, you are not able to change between those layers, you need first to change to google maps and then to the other ImageMapType layer.

### Steps to Reproduce

Add a map into a react application. then, add two or more layers with useMap() hook, for example

```tsx
import  { useEffect } from 'react';
import { useMap } from '@vis.gl/react-google-maps';

const loadOsmMap = () => {
  const openStreetMapType = new window.google.maps.ImageMapType({
    getTileUrl: (coord, zoom) => {
      return `https://tile.openstreetmap.org/${zoom}/${coord.x}/${coord.y}.png`;
      //return "https://tile.osmand.net/hd/" + zoom + "/" + coord.x + "/" + coord.y + ".png";
    },
    tileSize: new window.google.maps.Size(256, 256),
    maxZoom: 19,
    name: 'OpenStreetMaps',
  });
  return openStreetMapType;
};

export const MapLayers = () => {
  const map = useMap();
  useEffect(() => {
    if (!map) return;    
       map.mapTypes.set('osm-map', loadOsmMap());      
       map.mapTypes.set('second-map', otherLayerMap());    //User other tile layer map
       map.mapTypes.set('third-map', otherLayerMap());      //User other tile layer map
  }, [map]);
  return <></>;
};
```

then in Map Control add property

`mapTypeControlOptions={{mapTypeIds:["roadmap","satellite","osm-map","second-map","third-map"]}}`

then run app. You will see map type control. Try to change between your custom layers (pick osm-map then second-map) and will not work.

You always need to pick any google type for example roadmap and then you can change to your custom layer, but not between your layers.

### Environment

- Library version: 1.1.0
- Google maps version: weekly
- Browser and Version: Chrome last version
- OS: Mac

**Comment by usefulthink** [comment]
This sounds like it might not be related to the react-library, but rather the maps API itself. I'll try to reproduce this with the JS API first to see what's going on.

**Comment by ufoloko** [comment]
I already tried the same with JS API, and is working as expected

**Comment by usefulthink** [comment]
I can't really see anything wrong here. Do you notice anythong you're doing differently that these examples? Could it be that your Map or MapLayers components gets re-rendered or something like that?

Vanilla: https://codesandbox.io/p/sandbox/quirky-liskov-t3ym5p
React: https://codesandbox.io/p/devbox/wizardly-danilo-vkhlgq

**Comment by ufoloko** [comment]
im using library in this way

```
<APIProvider apiKey={GOOGLE_MAP_API_KEY}>
        <Map
          style={{ width: '100%', height: '100%' }}
          defaultCenter={{ lat: -0.10985147384067957, lng: -78.4422407690398 }}
          defaultZoom={13}
          gestureHandling={'greedy'}
          disableDefaultUI={false}
          options={mapOptions}
          mapTypeControl={true}                  
          reuseMaps={true}
          mapTypeControlOptions={{mapTypeIds:["roadmap","satellite","osm-map","lw-map"]}}
          >
        </Map>
      <MapLayers />
</APIProvider>
```

and in my MapLayers component this

```
import  { useEffect } from 'react';
import { useMap } from '@vis.gl/react-google-maps';

const loadLwMap = () => {
  const lwMapType = new window.google.maps.ImageMapType({
    getTileUrl: (coord, zoom) => {
      return `https://tile.othermapservice.org/${zoom}/${coord.x}/${coord.y}.png`;
    },
    tileSize: new window.google.maps.Size(256, 256),
    maxZoom: 19,
    name: 'Location World',
    
  });

  return lwMapType;
};

const loadOsmMap = () => {
  const openStreetMapType = new window.google.maps.ImageMapType({
    getTileUrl: (coord, zoom) => {
      return `https://tile.openstreetmap.org/${zoom}/${coord.x}/${coord.y}.png`;
    },
    tileSize: new window.google.maps.Size(256, 256),
    maxZoom: 19,
    name: 'OpenStreetMaps',
  });
  return openStreetMapType;
};

export const MapLayers = () => {
  const map = useMap();

  useEffect(() => {
    if (!map) return;    

    map.mapTypes.set('lw-map', loadLwMap());
    map.mapTypes.set('osm-map', loadOsmMap());      

  }, [map]);

  return <></>;
};
```

**Comment by usefulthink** [comment]
I don't think you do. The thing that is different is that you're using a mapId, if I remove it, the switching will work as expected. I already updated my vanilla example and it shows the exact same behaviour. 

This is an error in the Maps API itself, I'll create an issue for that.

What is interesting, is that its just the rendering that doesn't work:
- `maptypeid_changed` events are dispatched as expected
- after switching, `map.getMapTypeId()` returns the expected id

A hacky solution to this would be to implement a event-listener for the `maptypeid_changed` event, detect if a change that doesn't work happened and if thats the case, do something like `map.setMapTypeId('roadmap'); setTimeout(() => map.setMapTypeId('osm'),0);` to really do the switch.

**Comment by usefulthink** [comment]
https://issuetracker.google.com/issues/355451193

**Comment by ufoloko** [comment]
Thanks, i tried the vanilla code and have the same issue. Just additional information, if you add an advanced marked and you  you have an issue too when you move the map and you are using your custom maptype, markers move but when you release the map markers reset position.

**Comment by usefulthink** [comment]
Just got a note from the Google Maps Issue Tracking that the issue has been resolved in the latest version and I can no longer reproduce it.

https://issuetracker.google.com/issues/355451193
