### ISSUE TITLE
[Bug] Typescript: latLng are not accessible within MapMouseEvent as defined in it's interface

### ISSUE THREAD

**Issue by evgeniiarts** [visgl/react-google-maps#517]
### Description

I am working with typescript and wanted to use the google.maps.MapMouseEvent and get the latLng from it.
According to the interface, it should be available within the event directly. Yet I experience the following behavior, see the comments:
```tsx
const handleMapClick = (event: google.maps.MapMouseEvent) => {
        // Typescript is satisfied, but there is not latLng property in the event object
        console.log(event.latLng);

        // Typescript is not satisfied, but the code returns the coordinates as expected
        console.log(event.detail.latLng);
    };
```
    
I have checked the interface of the MapMouseEvent and apparently the latLng should be available within the event:

```tsx
export interface MapMouseEvent {
    /**
     * The corresponding native DOM event. Developers should not rely on
     * <code>target</code>, <code>currentTarget</code>,
     * <code>relatedTarget</code> and <code>path</code> properties being defined
     * and consistent. Developers should not also rely on the DOM structure of
     * the internal implementation of the Maps API. Due to internal event
     * mapping, the <code>domEvent</code> may have different semantics from
     * the {@link google.maps.MapMouseEvent} (e.g. a {@link
     * google.maps.MapMouseEvent} &quot;click&quot; may have a
     * <code>domEvent</code> of type <code>KeyboardEvent</code>).
     */
    domEvent: MouseEvent | TouchEvent | PointerEvent | KeyboardEvent | Event;
    /**
     * The latitude/longitude that was below the cursor when the event occurred.
     */
    latLng: google.maps.LatLng | null;
    /**
     * Prevents this event from propagating further.
     */
    stop(): void;
  }
```

### Steps to Reproduce

Steps to reproduce are:
1. Create a react typescript component and add a vis.gl/react-google-maps map to it.
2. Define a function which uses the google.maps.MapMouseEvent
3. Try to access event.latLng and you will get the typescript error I encounter.

### Environment

- Library version: 1.1.2
- Google maps version: weekly
- Browser and Version: doesn't matter
- OS: doesn't matter

**Comment by usefulthink** [comment]
`google.maps.MapMouseEvent` is the wrong type to use here. The Map component has its own event classes, since the events from the Maps API aren't really useful in our context.

If you instead use `import type {MapMouseEvent} from '@vis.gl/react-google-maps';` and use that, it will work as expected

**Comment by evgeniiarts** [comment]
@usefulthink Thank you kindly for the swift response, the new imported type indeed works as expected. Yet I am a little bit confused what the other interface is used for, as it appears to have the same structure (and content) as the imported one when console logged.

**Comment by evgeniiarts** [comment]
Oh I see, thanks for the explanation.
