### ISSUE TITLE
[Feat] Can we have an "onError" next to "onLoad"

### ISSUE THREAD

**Issue by marsonmao-trait** [visgl/react-google-maps#533]
### Target Use Case

Currently if we bump into https://github.com/visgl/react-google-maps/blob/main/src/components/api-provider.tsx#L178 then there's no way for consumer to retry or react; can we have an `onError` callback at this line?

### Proposal

```tsx

https://github.com/visgl/react-google-maps/blob/main/src/components/api-provider.tsx#L178

        } catch (error) {
          console.error(
            '<ApiProvider> failed to load the Google Maps JavaScript API',
            error
          );
          if (onError) {
            onError(error)
          }
        }
```

**Comment by usefulthink** [comment]
Yes, please! We definitely should have this.

Anyone wants to create a pull-request to address this?

**Comment by timmchi** [comment]
Hi, I'd like to submit a PR for this if that's ok.

**Comment by usefulthink** [comment]
Awesome, please go ahead! If you need help with anything, let me know.
