### ISSUE TITLE
[Bug] Google Maps Marker Deprecation warning: "Google Maps Marker is deprecated, use AdvancedMarkerElement."

### ISSUE THREAD

**Issue by MohammadGhorayshi** [visgl/react-google-maps#556]
### Description

I have this warning in my browser console:
`As of February 21st, 2024 (v3.56), google.maps.Marker is deprecated. We encourage you to transition to the new google.maps.marker.AdvancedMarkerElement class. Advanced markers provide substantial improvements over the legacy google.maps.Marker class.`

I need to remove this warning from browser console and I only replace one line in your source code and work without any warning.

Change `google.maps.Marker` to `google.maps.marker.AdvancedMarkerElement`

### Steps to Reproduce

You need to use <Marker /> component and see this warning.

### Environment

- Library version: 1.3
- Google maps version: weekly
- Browser and Version: Chrome Version 129.0.6668.60 (Official Build) (arm64)
- OS: Mac

**Comment by usefulthink** [comment]
Alternative: you can also change `import {Marker} from '@vis.gl/react-google-maps';` to `import {AdvancedMarker} from '@vis.gl/react-google-maps';` in your code and not use the legacy markers at all, as indicated by the deprecation-warning.
