### ISSUE TITLE
[Bug] AdvancedMarker custom icon not appearing

### ISSUE THREAD

**Issue by usefulthink** [visgl/react-google-maps#560]
### Discussed in https://github.com/visgl/react-google-maps/discussions/558

<div type='discussions-op-text'>

<sup>Originally posted by **Remarketeer** October  2, 2024</sup>
I'd like to ask for some help!

So a week ago I left my maps page alone to work on other stuff, but suddenly my markers disappeared. For some context, I have an array that I load information from and use .map to create markers for each entry. After some trial and error, I realized that it just wasn't accepting image inputs, e.g <img src='' width=.../>. 

I've attempted to load the image on my other pages and that was fine. I've attempted to load Pin objects and that worked too, I've tried loading just a singular marker using an image source but it behaves the same way. Loading the image directly on the maps page also seems to work so the issue shouldn't be that.  I'm quite stumped as to where it could have gone wrong.

Currently the data seems to have been loaded into the map as I've printed it to the console, but the marker just isn't appearing.</div>

**Comment by mrMetalWood** [comment]
@Remarketeer I found an issue that would prevent a marker from showing when its width was set via CSS with a class on the `AdvancedMarker` element, but I'm not sure if that fits the issue you were describing. From the snippet you provided in the discussion it does not seem like it.

Could you provide a basic running example (on codesandbox or similar) where the issue exists?

**Comment by usefulthink** [comment]
@Remarketeer with the new version 1.4.0, this should be fixed. Can you re-check if you're still seeing the problem?
