### ISSUE TITLE
The splatting operator '@' cannot be used to reference variables  in an expression. '@vis' can be used only as an argument to a c ommand. To reference variables in an expression use '$vis'

### ISSUE THREAD

**Issue by hitecSmartHome** [visgl/react-google-maps#580]
### Description

At line:1 char:13
+ npm install @vis.gl/react-google-maps
+             ~~~~
The splatting operator '@' cannot be used to reference variables
 in an expression. '@vis' can be used only as an argument to a c
ommand. To reference variables in an expression use '$vis'.      
    + CategoryInfo          : ParserError: (:) [], ParentContai  
   nsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted

### Steps to Reproduce

npm install @vis.gl/react-google-maps

### Environment

- Library version:
- Google maps version: weekly
- Browser and Version:
- OS:

**Comment by usefulthink** [comment]
@hitecSmartHome was that PowerShell / Windows?

**Comment by hitecSmartHome** [comment]
Yes. It was vscode terminal on windows. But as soon as i submitted the issue, seen the solution in the Readme. Sorry for that

**Comment by usefulthink** [comment]
No worries 👍
