### ISSUE TITLE
[Feat] Requesting React 16 types support

### ISSUE THREAD

**Issue by mereh74** [visgl/react-google-maps#583]
### Target Use Case

I would like to use this library for development with Google Maps, however, I'm currently unable to as my project uses React 16 and `React.JSX` is not exported in React 16 types.  I'm requesting a change in this library to use `React.ReactElement` in order to maintain type compatibility.  

### Proposal

This library is exporting `info-window` and the map index as `React.JSX.Element`.  This is not exported in React 16 `types`.  Requesting that these be exported as `React.ReactElement` instead.

**Comment by usefulthink** [comment]
This appears to be the type that typescript infers on build from our components. Adding an explicit type to our components (ie.g. `const InfoWindow: FunctionComponent = ...`) seems to solve this in the generated .d.ts files.
