### ISSUE TITLE
[Feat] Support nextjs 15

### ISSUE THREAD

**Issue by nilsingwersen** [visgl/react-google-maps#596]
### Target Use Case

If you use nextjs 15 with react 19 and you try to install the library you get an error because of the peer dependency.
shadcn has a great article about this: https://ui.shadcn.com/docs/react-19

### Proposal

As a first step add react 19 as peer dependency.

**Comment by usefulthink** [comment]
I find it hard to understand why `"react": ">=16.8.0"` doesn't match the versions `19.0.0-rc-*`, but changing this should be fairly straightforward if the library does in fact work without problems in react 19.

**Comment by mrMetalWood** [comment]
Came across this last week as well. I'm working on a basic NextJS example at the moment. Will address this when adding the example

**Comment by camilo86** [comment]
Came across this problem in next 15. For now, you can install with `npm install @vis.gl/react-google-maps --force`

**Comment by mrMetalWood** [comment]
This should be solved with `1.4.1` (just released)
