### ISSUE TITLE
[Bug] onMouseEnter and onMouseLeave not working with AdvancedMarker

### ISSUE THREAD

**Issue by isaacpresidium** [visgl/react-google-maps#601]
### Description

I just can't get these functions to do anything when used with my AdvancedMarker component. I've tried a lot of things but still can't figure out why this is happening. I'm on the latest 1.4 version

### Steps to Reproduce

Here's what my AdvancedMarker code looks like: 

```typescript
import React, { useState, useEffect } from 'react';
import { AdvancedMarker, Pin, useAdvancedMarkerRef, InfoWindow, AdvancedMarkerAnchorPoint } from '@vis.gl/react-google-maps';
import { Place } from '.';

interface Marker extends Place {
  children?: React.ReactNode
}

const CustomMarker = (props: Marker) => {
  const [showInfoWindow, setShowInfoWindow] = useState(false)
  const [showInfoWindowClicked, setShowInfoWindowClicked] = useState(false)
  const [pos, setPos] = useState<{ lat: number, lng: number } | null>(null)
  const [markerRef, marker] = useAdvancedMarkerRef()

  useEffect(() => {
    if (props.pos.lat != undefined && props.pos.lng != undefined)
      setPos(props.pos)
  }, [props.pos]);

  return (
    <>
      <AdvancedMarker
        key={props.id}
        position={pos}
        ref={markerRef}
        onClick={() => setShowInfoWindowClicked(!showInfoWindowClicked)}
        title={props.info}
        onMouseEnter={() => setShowInfoWindow(true)}
        onMouseLeave={() => setShowInfoWindow(false)}
        anchorPoint={["50%", "100%"]}
      >
        <Pin background={'#FBBC04'} glyphColor={'#000'} borderColor={'#000'} />
        <div className='w-max justify-center bg-white/[.85] text-center absolute left-[-50%]'>{props.info}</div>
        {(showInfoWindow || showInfoWindowClicked) && (
          <InfoWindow anchor={marker} position={props.pos} onCloseClick={() => setShowInfoWindowClicked(false)}>
            {props.children ?
              <h5>{props.children}</h5> :
              <h5>{props.info}</h5>}
          </InfoWindow>
        )}
      </AdvancedMarker>
    </>
  );


}
export default CustomMarker;
```

Here is where the map is rendering, the CustomMarker is being passed in as children to this map:

```typescript
const renderMap = () => {
    return (
      <Map
        defaultZoom={zoom}
        defaultCenter={props.center}
        disableDefaultUI={false}
        style={{
          height: "50vh",
          width: "100%",
        }}
        mapId={"2b790ebe9736cc6a"}
      >
        {props.children}
      </Map>
    );
  };
```

If this is insufficient I could upload a CodeSandbox of my issue, but I just wanted to know if there is something I'm missing or is this just bugged?

### Environment

- Library version: @vis.gl/react-google-maps@1.4.0
- Google maps version: weekly
- Browser and Version: Chrome 130.0.6723.117
- OS: Windows 10

**Comment by mrMetalWood** [comment]
Hi @isaacpresidium,

I tried to reproduce your issue in a Codesandbox here: https://codesandbox.io/p/devbox/marker-issue-956hxz?file=%2Fsrc%2Fcustom-marker.tsx%3A29%2C14&workspaceId=308f8424-7fda-45b9-be07-d27ae10b961b

It seems to be working as expected for me. Did I reproduce your setup correctly? If not it would be greatif you could provide a running example where the issue occurs for you. Does it work for you in the sandbox as well? 


https://github.com/user-attachments/assets/09791297-b687-4b8c-b837-7ef2b14bfb13

**Comment by isaacpresidium** [comment]
Huh seems to work fine on my machine after all. I think when I updated the library I neglected to restart the web server which would explain why the onMouseEnter/Leave weren't registering anything. Thank you for checking, though! I'll close this
