### ISSUE TITLE
[Bug] `google.maps.Marker is deprecated`

### ISSUE THREAD

**Issue by strarsis** [visgl/react-google-maps#614]
### Description

When using the `<AdvancedMarker />` component, a warning is emitted in console:
````
As of February 21st, 2024, google.maps.Marker is deprecated. Please use google.maps.marker.AdvancedMarkerElement instead. At this time, google.maps.Marker is not scheduled to be discontinued, but google.maps.marker.AdvancedMarkerElement is recommended over google.maps.Marker. While google.maps.Marker will continue to receive bug fixes for any major regressions, existing bugs in google.maps.Marker will not be addressed. At least 12 months notice will be given before support is discontinued. Please see https://developers.google.com/maps/deprecations for additional details and https://developers.google.com/maps/documentation/javascript/advanced-markers/migration for the migration guide.
````

### Steps to Reproduce

1. Add an `<AdvancedMarker />` component to the `<Map>` component, run the app.

### Environment

- Library version: `1.4.0`
- Google maps version: `3.59.1`
- Browser and Version: `Chrome`
- OS: `Windows 10`

### Logs

```text
As of February 21st, 2024, google.maps.Marker is deprecated. Please use google.maps.marker.AdvancedMarkerElement instead. At this time, google.maps.Marker is not scheduled to be discontinued, but google.maps.marker.AdvancedMarkerElement is recommended over google.maps.Marker. While google.maps.Marker will continue to receive bug fixes for any major regressions, existing bugs in google.maps.Marker will not be addressed. At least 12 months notice will be given before support is discontinued. Please see https://developers.google.com/maps/deprecations for additional details and https://developers.google.com/maps/documentation/javascript/advanced-markers/migration for the migration guide.
```

**Comment by mrMetalWood** [comment]
This warning should only be there when using the `<Marker />` component not the `<AdvancedMarker />`. The `<AdvancedMarker />` should be working fine. Can you double check if you are really using the AdvancedMarker and seeing this warning?

We should add a banner in our docs for the `<Marker />`  with this deprecation warning as well to encourage users to use the new `AdvancedMarker`

**Comment by strarsis** [comment]
> Can you double check if you are really using the AdvancedMarker and seeing this warning?
You are correct, `vite` hot reloading had issues, hence the Marker component was still used on the page.
With `AdvancedMarker` the warning is not logged.
