### ISSUE TITLE
[Bug] Recent change a5b035986872b3abb8c28d6659034c2a897476a3 seems to break ref prop on AdvancedMarkers

### ISSUE THREAD

**Issue by jisuo** [visgl/react-google-maps#617]
### Description

ref prop is no longer valid prop on AdvancedMarker after this commit: https://github.com/visgl/react-google-maps/commit/a5b035986872b3abb8c28d6659034c2a897476a3

### Steps to Reproduce

Use version 1.4.1 and try to use ref prop on AdvancedMarker

```
import { AdvancedMarker } from '@vis.gl/react-google-maps'

<AdvancedMarker
      position={{ lat: lng }}
      draggable={false}
      ref={(marker) => console.log(marker)}
    >
      <div>Test</div>
    </AdvancedMarker>
```
    
    
  error is:
  
  ```Type '{ children: Element; position: { lat: number; lng: number; }; draggable: false; onClick: () => void; ref: (marker: any) => void | undefined; }' is not assignable to type 'IntrinsicAttributes & Omit<AdvancedMarkerElementOptions, "gmpDraggable" | "gmpClickable" | "content" | "map" | "collisionBehavior"> & AdvancedMarkerEventProps & { ...; } & { ...; }'.
  Property 'ref' does not exist on type 'IntrinsicAttributes & Omit<AdvancedMarkerElementOptions, "gmpDraggable" | "gmpClickable" | "content" | "map" | "collisionBehavior"> & AdvancedMarkerEventProps & { ...; } & { ...; }'.ts(2322)  
```

### Environment

- Library version: 1.4.1
- Google maps version: weekly
- Browser and Version: Chrome Version 131.0.6778.86 (Official Build) (x86_64)
- OS: Mac OS 15.1.1 (24B91)

**Comment by usefulthink** [comment]
Oh wee, sorry about this. I can probably publish a new version tomorrow, until then you can use `@ts-ignore` or `@ts-expect-error` to get around the error-message.
