### ISSUE TITLE
How to update the map after a change in state?

### ISSUE THREAD

**Issue by MauricioRobayo** [visgl/react-google-maps#65]
Hello!

I'm testing the library and wanted to add custom Zoom-in Zoom-out buttons, but the map does not update when the zoom values updates.

I created a simple GoogleMap componet like this:

```ts
"use client";

import { APIProvider, Map } from "@vis.gl/react-google-maps";

export default function GoogleMap({ zoom }: { readonly zoom: number }) {
  const position = { lat: 53.54, lng: 10 };

  return (
    <APIProvider apiKey={process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY ?? ""}>
      <div className="aspect-video">
        <Map zoom={zoom} center={position} />
      </div>
    </APIProvider>
  );
}
```

and then used it on another component like this:

```ts
"use client";

import { useState } from "react";
import GoogleMap from "./GoogleMap";

export default function Home() {
  const [zoom, setZoom] = useState(10);
  return (
    <>
      <GoogleMap zoom={zoom} />
      <button
        onClick={() => setZoom(zoom + 1)}
      >
        Zoom in
      </button>
      <button
        onClick={() => setZoom(zoom - 1)}
      >
        Zoom out
      </button>
      <div>Zoom: {zoom}</div>
    </>
  );
}
```

When I change the zoom using the parent compent the child component does not update to reflect the new zoom value.

Here is a test repository: https://github.com/MauricioRobayo/google-maps-test

**Comment by usefulthink** [comment]
The fix for this is in the works here: #64. Should be ready to merge later this week.

**Comment by usefulthink** [comment]
This should be resolved with https://github.com/visgl/react-google-maps/commit/0b1d800dc5e4b9bf0b1ddb42b9fed392b23b8dae in v0.3. Let me know if you're still seeing problems.

**Comment by MauricioRobayo** [comment]
It is working as expected now, thanks @usefulthink !
