### ISSUE TITLE
What is the plan for stable version?

### ISSUE THREAD

**Issue by aleksandrlat** [visgl/react-google-maps#66]
I'm excited to see this library
Is there a plan with clear milestones and ETA for first stable version?
So we can help to focus on these milestones

**Comment by usefulthink** [comment]
Very good question :) 

Right now we don't have such a plan in writing, but I realize it would be a good idea to document the open tasks here as issues. I can hopefully take care of that in the next few days and give you an updated answer..

The general idea was to gather some real-world feedback with the pre-1.0 versions, stabilize what we have right now (functionality, examples and documentation) and then release the 1.0 version.

**Comment by aleksandrlat** [comment]
Thank you @usefulthink!
And we can help with something

**Comment by usefulthink** [comment]
I wrote a bit more about this here: https://github.com/visgl/react-google-maps/discussions/100
