### ISSUE TITLE
How do i detect zoom changes?

### ISSUE THREAD

**Issue by B45i** [visgl/react-google-maps#70]
Is there any event that I can use to detect zoom changes?
I couldn’t find anything in the docs and type.d.ts file.

**Comment by usefulthink** [comment]
I'm working on this right now: #64

There will be an `onZoomChanged` event-prop that you can use. The only thing missing in the PR above is a custom event-implementation since the few events the maps-API provides aren't very useful in our context. I should be done with that later today.

**Comment by usefulthink** [comment]
In version v0.3 this should now work:

```tsx
function Component() {
  const [zoom, setZoom] = useState(5);

  return (
    <Map
        center={{lat: 0, lng: 20}}
        zoom={zoom}
        onZoomChanged={ev => setZoom(ev.detail.zoom)}>
    </Map>
  );
}
```
