### ISSUE TITLE
Map component not applying MapStyles passed into `styles` prop

### ISSUE THREAD

**Issue by TaqwaR** [visgl/react-google-maps#77]
Hello,

I am trying to turn off the Points of Interest (POI) on the `Map` component, but there's an issue  with the prop not being applied. Here is my code snippet:

```javaScript

import React, { useState } from 'react';
import { APIProvider, Map, AdvancedMarker, Pin, InfoWindow } from '@vis.gl/react-google-maps';

 <APIProvider apiKey={API_KEY}>
        <Map
          onLoadMap={onLoad}
          zoom={zoom}
          center={center}
          disableDefaultUI
          style={{height: '100%', width: '100%'}}
         // issue is with the below prop - not being applied
          styles={[
            {
              featureType: 'poi',
              elementType: 'labels',
              stylers: [{ visibility: 'off' }],
            },
          ]}
        >
    <AdvancedMarker
      position={{ lat: latitude, lng: longitude }}
      key={key}
      title={title}
    >
       <Pin />
    </AdvancedMarker>
    <InfoWindow>{Text}</InfoWindow>
</Map>
</APIProvider>

```

I've tried variations of the styles prop as well. As in, I've tried:

```javaScript
            {
              featureType: 'poi',
              elementType: 'labels',
              stylers: [{ visibility: 'off' }],
            },
```

```javaScript
            {
              featureType: 'poi.business',
              elementType: 'labels',
              stylers: [{ visibility: 'off' }],
            },
```

```javaScript
            {
              featureType: 'poi.business',
              stylers: [{ visibility: 'off' }],
            },
```

```javaScript
            {
              featureType: 'poi.business',
              elementType: 'all',
              stylers: [{ visibility: 'off' }],
            },
```

None of these result in turning of the `poi` visibility on the map as far as I can see.  I've double checked the Google Map docs as well to make sure of syntax/format: https://developers.google.com/maps/documentation/javascript/style-reference

For clarification, I would like to "turn off" all of these gray colored markers, and only have the black Marker (with the `4`) showing on the map.

![Screenshot 2023-11-09 at 2 42 37 PM](https://github.com/visgl/react-google-maps/assets/17800509/7306f3dd-69a6-484a-8910-de5f904923ae)

**Comment by usefulthink** [comment]
Thanks for spotting this! I've only tested with cloud based styling so far, so haven't come across this.

**Comment by usefulthink** [comment]
I tested that locally, and for me everything seems to be working. Are you on the latest version (check by running `npm outdated`, that shouldn't have a line for @vis.gl/react-google-maps)? There might have been changes today that fixed that already... 

Otherwise, what is logged to the console when you add 
`onRenderingTypeChanged={ev => console.log('renderingType', ev.map.getRenderingType())}` to your Map?

**Comment by TaqwaR** [comment]
@usefulthink I updated to version `0.3.2` (was on ` 0.1.2` before), but still getting all of these orange, gray, blue, etc `poi` markers outside of my custom ones.

![Screenshot 2023-11-10 at 10 54 46 AM](https://github.com/visgl/react-google-maps/assets/17800509/1826b07a-3708-4d14-aba4-389a61f5cd22)

Though, I did add this prop `onRenderingTypeChanged={ev => console.log('renderingType', ev.map.getRenderingType())}` like you suggested, and I got this logged in the console: `renderingType RASTER` - does that tell you anything else?

**Comment by usefulthink** [comment]
No, that should be correct. I'm a bit out of ideas here. Can you try to create a codesandbox to reproduce this issue?

**Comment by usefulthink** [comment]
I updated [this example](https://visgl.github.io/react-google-maps/examples/change-map-styles) to include switching to locally styled maps so we can see it working. Still curious to find out what is causing that behaviour for you.

**Comment by TaqwaR** [comment]
@usefulthink Thank you for your help! 

I ended up figuring this out so I will close this issue. 

The `styles` weren't showing up because I am using an `AdvancedMarker` component in my `Map`,  and `AdvancedMarkers` require a `mapId` prop. And if there's a `mapId` prop present on the `Map`, then the `styles` prop _must_ be set in the Google Map cloud console, and not set inline. Which is what I was doing.

**Comment by victoriamoret** [comment]
I faced the same issue of the map styles not being applied when using advanced markers, and fixed it by applying the styles this way:

```
const styledMapType = new google.maps.StyledMapType(MAP_SETTINGS);
map.mapTypes.set('styled_map', styledMapType);
map.setMapTypeId('styled_map');
```

In a useEffect with `map` dependency from `useMap()` : [https://visgl.github.io/react-google-maps/docs/api-reference/hooks/use-map](https://visgl.github.io/react-google-maps/docs/api-reference/hooks/use-map)

MAP_SETTINGS is my array of styles from [https://mapstyle.withgoogle.com/](https://mapstyle.withgoogle.com/) (not cloud based)

**Comment by m-nathani** [comment]
Facing the same issue here... 

However, is this how its supposed to work the maps, or it something specific to `@visgl/react-google-maps` ?  🤔 
> AdvancedMarkers require a mapId prop. And if there's a mapId prop present on the Map, then the styles prop must be set in the Google Map cloud console

**Comment by usefulthink** [comment]
That is a limitation coming from the Maps API, not specific to this library.

**Comment by mxmzb** [comment]
> That is a limitation coming from the Maps API, not specific to this library.

but why does this solution work?

> I faced the same issue of the map styles not being applied when using advanced markers, and fixed it by applying the styles this way:
> 
> ```
> const styledMapType = new google.maps.StyledMapType(MAP_SETTINGS);
> map.mapTypes.set('styled_map', styledMapType);
> map.setMapTypeId('styled_map');
> ```
> 
> In a useEffect with `map` dependency from `useMap()` : https://visgl.github.io/react-google-maps/docs/api-reference/hooks/use-map
> 
> MAP_SETTINGS is my array of styles from https://mapstyle.withgoogle.com/ (not cloud based)

The problem for me with this is that I could easily grab some style from https://snazzymaps.com/style/72543/assassins-creed-iv or so, but in Google Cloud console now there is no more option to import json (https://issuetracker.google.com/issues/323011272?pli=1). While the solution above works, I wonder if that's gonna count as 2 map loads billing wise every time this code runs...?

**Comment by karldanninger** [comment]
When I implement this, and a user taps a button the change to a different 'styled_map' the labels are lost (road names, neighbourhoods, etc). Have any of you experienced that as well?

**Comment by managervcf** [comment]
@victoriamoret Thank you for the solution—it works perfectly. However, a warning appears every time a map loads:

```console
Google Maps JavaScript API: A Map's custom map types cannot be set when a mapId is present.  
When a mapId is present, map styles are controlled via the cloud console. 
```

I suspect Google Maps might block this workaround in the future.

It’s unfortunate that the option to import map styles from a JSON file has been removed.
