### ISSUE TITLE
[Feat] Adding missing components from @googlemaps/extended-component-library such as split-layout

### ISSUE THREAD

**Issue by tobiasbueschel** [visgl/react-google-maps#91]
### Target Use Case

Thanks for this library - is there a plan to integrate the remaining components from the [@googlemaps/extended-component-library](https://github.com/googlemaps/extended-component-library) such as the [gmpx-split-layout](https://github.com/googlemaps/extended-component-library/blob/main/src/split_layout/README.md) or the [gmpx-place-overview](https://github.com/googlemaps/extended-component-library/blob/main/src/place_overview/README.md) components?

![split-layout](https://github.com/googlemaps/extended-component-library/raw/main/src/split_layout/doc_src/split-layout.png)

### Proposal

It would be great to find a way to keep both libraries in sync :)

**Comment by usefulthink** [comment]
There are plans to allow at least some degree of interoperability with the official web-components (both `gmp-*` and `gmpx-*`) at some point. But for that we'll have to wait for the WCs to become stable (currently everything in that regard is still in alpha or preview phases) and figure out some things about how this integration would work with regards to state handling and such.

I imagine this roughly as users being able to just add the WCs to the `<APIProvider>` and `<Map>` react components and our library providing some sort of shim necessary for them to work like they do with the `<gmp-map>` WC.

This would probably only extend to components that are isolated in nature and either act as a single control with limited state (e.g. `gmpx-place-picker` or `gmpx-place-overview`) or add something to an existing map-instance (e.g. `gmpx-route-overview`).   

It's unlikely we'll be supporting something like the `gmpx-split-layout` or `gmpx-overlay-layout` components.

This is also a bit dependent on improved web-component support in react, which I read will be coming with react 19.0 (whenever that might be).

**Comment by kwnevarez** [comment]
Take a look at this example:
https://visgl.github.io/react-google-maps/examples/extended-component-library
