### ISSUE TITLE
[Bug] You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors

### ISSUE THREAD

**Issue by BhaskaranR** [visgl/react-google-maps#97]
### Description

i am using useGoogleMapsScript for the auto complete places api on the same page. this cause issues with with the map. 

can we check if the script has already been loaded to avoid this error?

### Steps to Reproduce

```
export function GoogleMapsScript({ googleMapsApiKey, children }: LoadScriptProps) {
  const { isLoaded, loadError } = useGoogleMapsScript({
    googleMapsApiKey: googleMapsApiKey!,
    libraries,
  })

 <APIProvider apiKey={env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}>
</APIProvider>
```
conflicts...

### Environment

- Library version: latest
- Google maps version: weekly
- Browser and Version: chrome
- OS:mac

**Comment by usefulthink** [comment]
Can you tell me where the `useGoogleMapsScript` hook is coming from? 

> can we check if the script has already been loaded to avoid this error?

The thing is, at the point of Initialization, neither of the two has already loaded (or rather, finished loading) the Maps API. Apparently both have created a script tag and started downloading the Maps API JS. This is why you're seeing the error.

Internally, we're using the `google.maps.importLibrary` function to load the maps API and it's libraries.
This is the recommended way to load it these days. In fact, the code you find [here](https://github.com/visgl/react-google-maps/blob/main/src/libraries/google-maps-api-loader.ts#L74) is just a refactored version of the [official library loader](https://developers.google.com/maps/documentation/javascript/load-maps-js-api).

We even added [a check that will use any existing `importLibrary` function](https://github.com/visgl/react-google-maps/blob/main/src/libraries/google-maps-api-loader.ts#L42-L45).

If the other library you're using would do the same, it would probably be enough to be compatible with our library.

**Comment by BhaskaranR** [comment]
using this one - use-google-maps-script [link](https://github.com/leighhalliday/use-google-maps-script)

**Comment by usefulthink** [comment]
Interesting, ok. 
But that does't seem to do much what this library doesn't already do, what do you need it for?

**Comment by BhaskaranR** [comment]
got it. i removed the library dont face this issue anymore. thanks for the clarification.
